event_management_ (copy)/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView
from django.urls import reverse_lazy
admin.site.site_header = "Event Management Admin"
urlpatterns = [
     path('admin/event_management_application/systemconfigs/', RedirectView.as_view(url='/admin/event_management_application/systemconfigs/1/change/', permanent=False), name='sysconfig'),  
    path("admin/", admin.site.urls),
    path("",include("event_management_application.urls")),
    path("payment/",include("event_management_application.urls")),
    path("razorpay/",include("event_management_application.urls")),
    path("freepay/",include("event_management_application.urls")),
    path("success/",include("event_management_application.urls")),
    path("contact_us/",include("event_management_application.urls")),
    path("event_detail/",include("event_management_application.urls")),
    path("tickets/",include("event_management_application.urls")),
    path("popup_data/<int:id>",include("event_management_application.urls")),
    path("customer/",include("event_management_application.urls")),
    path("analysis/",include("event_management_application.urls")),
    path("redeemed/",include("event_management_application.urls")),
    path("downloadpdf/",include("event_management_application.urls")),
    path("recent_transactions/",include("event_management_application.urls")),
    path("choices/",include("event_management_application.urls")),
  
]

event_management_application/models.py
from django.db import models
from django.core.validators import *
from django.utils import timezone
from django.db import models
from django.db.models.fields import CharField
from django.utils.translation import gettext_lazy as _
from .scripts.constants import PaymentStatus
from django.core.exceptions import ValidationError
# from django.contrib.postgres.fields import ArrayField

class Employee(models.Model):
    employee_id = models.IntegerField(primary_key=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    role = models.CharField(max_length=50)
    address = models.CharField(max_length=50)
    contact_number = models.IntegerField()
    email = models.CharField(max_length=50)
    profile = models.CharField(max_length=50)
    is_active = models.IntegerField(default = 1,
                                   blank = True,
                                    null = True,
                                    help_text ='1->Active, 0->Inactive', 
                                    choices =(
                                    (1, 'Active'), (0, 'Inactive')
                                    ))
    deleted = models.IntegerField(default = 0,
                                   blank = True,
                                    null = True,
                                    help_text ='1->yes, 0->No', 
                                    choices =(
                                    (1, 'yes'), (0, 'No')
                                    ))
    created_on = models.DateTimeField(default = timezone.now)
    updated_on = models.DateTimeField(default = timezone.now,
                                    null = True, 
                                    blank = True
                                    )
    def __str__(self):
        return self.first_name
    
    class Meta:
        db_table = "employee"

class Category(models.Model):
    category_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    parent_category = models.IntegerField()
    path = models.CharField(max_length=50)
    description = models.CharField(max_length=50)
    is_active = models.IntegerField(default = 1,
                                   blank = True,
                                    null = True,
                                    help_text ='1->Active, 0->Inactive', 
                                    choices =(
                                    (1, 'Active'), (0, 'Inactive')
                                    ))
    deleted = models.IntegerField(default = 0,
                                   blank = True,
                                    null = True,
                                    help_text ='1->yes, 0->No', 
                                    choices =(
                                    (1, 'yes'), (0, 'No')
                                    ))
    def __str__(self):
        return self.name
    
    class Meta:
        db_table = "category"

class Client(models.Model):
    client_id = models.AutoField(primary_key=True)
    client_name = models.CharField(max_length=50)
    contact_number = models.IntegerField(validators=[MaxLengthValidator(10)])
    email = models.EmailField()
    created_on = models.DateTimeField(default = timezone.now)
    updated_on = models.DateTimeField(default = timezone.now,
                                    null = True, 
                                    blank = True
                                    )
    def __str__(self):
        return self.client_name
    
    class Meta:
        db_table = "client"

class Event(models.Model):
    event_id = models.AutoField(primary_key=True)
    # event_location_id = models.ForeignKey(EventLocation, on_delete=models.CASCADE)
    # location_id = models.ForeignKey("EventLocation", on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=50,default='None')
    Event_from = models.DateTimeField()
    Event_to = models.DateTimeField()
    Image = models.ImageField(default='None', upload_to='static/uploads/images/')
    has_tickets = models.BooleanField(default=True)
    total_count = models.PositiveBigIntegerField(default=0)
    remain_tickets = models.PositiveBigIntegerField(default=0)
    total_cost = models.PositiveBigIntegerField(default=0)
    total_price = models.PositiveBigIntegerField(default=0)
    # event_grand_total = models.PositiveBigIntegerField(null=True, blank=True,default=   0)
    paid_amount = models.PositiveBigIntegerField(default=0)
    pending_amount = models.PositiveBigIntegerField(default=0)
    has_sub_events = models.CharField(default='Yes', choices=(('Yes', 'Yes'), ('No', 'No')), max_length=3)

    created_on = models.DateTimeField(default = timezone.now)
    updated_on = models.DateTimeField(default = timezone.now,
                                    null = True, 
                                    blank = True
                                    )
    is_deleted = models.BooleanField(default=False)
    
    def __str__(self):
        return self.name
    
    class Meta:
        db_table = "event"

class EventLocation(models.Model):
    # event_location_id = models.IntegerField(primary_key=True)
    location_id = models.ForeignKey(Event, on_delete=models.CASCADE)
    # event_id = models.IntegerField()
    title = models.CharField(max_length=50,default='None')
    address = models.CharField(max_length=250,default='None')
    street_detail = models.CharField(max_length=50,default='None')
    city = models.CharField(max_length=50, default='None')
    state = models.CharField(max_length=50,default='None')
    country = models.CharField(max_length=50,default='India')
    zipcode = models.IntegerField(default=0)
    location_link = models.CharField(max_length=200,default='None')
    def __str__(self):
        return self.title
    
    class Meta:
        db_table = "event_location"

class Subloca(models.Model):
    address = models.CharField(max_length=250)
    event_id = models.ForeignKey(Event, on_delete=models.CASCADE)
    def __str__(self):
        return self.address
    
    class Meta:
        db_table="sub_location"

class EventCategory(models.Model):
    event_id = models.ForeignKey(Event, on_delete=models.CASCADE)
    catgory_id = models.ForeignKey(Category, on_delete=models.CASCADE)
    def __str__(self):
        return self.event_id
    
    class Meta:
        db_table = "event_category"

class EventEmployee(models.Model):
    event_id = models.ForeignKey(Event, on_delete=models.CASCADE)
    employee_id = models.ForeignKey(Employee, on_delete=models.CASCADE)
    role_note = models.CharField(max_length=50)
    def __str__(self):
        return self.event_id
    
    class Meta:
        db_table = "event_employee"

class Tickets(models.Model):
    ticket_id = models.AutoField(primary_key=True)
    event_id = models.ForeignKey(Event, on_delete=models.CASCADE)
    ticket_type = models.CharField(max_length=50, choices=( ('VIP', 'VIP'), ('BASE', 'BASE')),blank=True,null=False)
    ticket_price = models.IntegerField()
    ticket_count = models.IntegerField()
    ticket_description = models.CharField(max_length=50)
    created_on = models.DateTimeField(default = timezone.now)
    updated_on = models.DateTimeField(default = timezone.now,
                                    null = True, 
                                    blank = True
                                    )
    def __str__(self):
        return f"{self.event_id}--{self.ticket_type}--{self.ticket_count} "
    
    class Meta:
        db_table = "tickets"
    
class Order(models.Model):
    location_link = models.CharField(max_length=200,default='None')
    event_id = models.IntegerField()

    user_name = models.CharField(max_length=50)
    payment_event_id = models.IntegerField(default=0, null=False, blank=False)
    amount = models.FloatField(_("Amount"), null=True, blank=True)
    status = CharField(
        _("Payment Status"),
        default=PaymentStatus.PENDING,
        max_length=254,
        blank=False,
        null=False,
    )
    provider_order_id = models.CharField(
        _("Order ID"), max_length=40, null=False, blank=False
    )
    payment_id = models.CharField(
        _("Payment ID"), max_length=36, null=False, blank=False
    )
    signature_id = models.CharField(
        _("Signature ID"), max_length=128, null=False, blank=False
    )
    email = models.CharField(_("Email"), default='demo@abc.com' , max_length=128, null=False, blank=False)

    user_phone = models.IntegerField(_("Phone"), null=False, blank=False)
    
    event_name = models.CharField(_("Event Name"), max_length=128, null=False, blank=False)

    event_From = models.CharField(_("Event Date"), max_length=128, null=False, blank=False)

    ticket_type = models.CharField(_("Ticket Type"), max_length=128, null=True, blank=True)

    ticket_count = models.IntegerField(_("Ticket Count"), null=False, blank=False)

    ticket_used = models.CharField(_("Ticket Used"),default="No", max_length=128, null=True, blank=True)

    save_hash = models.CharField(_("Save Hash"), max_length=255, null=True, blank=True)

    save_url = models.CharField(_("Save URL"), max_length=255, null=True, blank=True)

    created_on = models.DateTimeField(default = timezone.now)
    updated_on = models.DateTimeField(default = timezone.now,
                                    null = True,
                                    blank = True
                                    )
    email_sent = models.BooleanField(default=False)
   
    def __str__(self):
        return f"{self.payment_id}--{self.save_hash}"
    
    class Meta:
        db_table = "order"
    
class Seats(models.Model):
    event_id = models.ForeignKey(Event, on_delete=models.CASCADE)
    seat_name = models.CharField(max_length=50)
    user_name = models.CharField(max_length=50)
    seat_count = models.IntegerField()
    created_on = models.DateTimeField(default = timezone.now)

templates/event_catagory/catagory.html
{% extends 'adminlte/base.html' %}

{% block content %}
<div id="content-main" class="container-fluid">
    
    
    
    <div class="row">
        <div class="col-md-12">
            <form enctype="multipart/form-data" action="" method="post" id="category_form" novalidate=""><input type="hidden" name="csrfmiddlewaretoken" value="o1ZLyPYk0w7YD0r7I0Uta2gGfsZzm0qxtjgAPvwkzuOjPAHCA6Gv1W8M2cz29fhX">

                
                
                
                

                
                
                <div class="card card-info">
    <div class="card-header bg-primary">
        <h3 class="card-title"></h3>
        
        <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i>
            </button>
          </div>
    </div>
    <div class="card-body">
        
        <div class="form-group row form-row field-name">
            
            
            <label for="name" class="col-sm-2 col-form-label"><label class="required" for="id_name">Name:</label></label>
            <div class="col-sm-10">
                

                
                <input type="text" name="name" class="vTextField" maxlength="50" required="" id="id_name">
                
                
                
            </div>


            
        </div>
        
        <div class="form-group row form-row field-image">
            
            
            <label for="image" class="col-sm-2 col-form-label"><label class="required" for="id_image">Image:</label></label>
            <div class="col-sm-10">
                

                
                <input type="file" name="image" accept="image/*" required="" id="id_image">
                
                
                
            </div>


            
        </div>
        
        <div class="form-group row form-row field-parent_category">
            
            
            <label for="parent_category" class="col-sm-2 col-form-label"><label class="required" for="id_parent_category">Parent category:</label></label>
            <div class="col-sm-10">
                

                
                <input type="number" name="parent_category" class="vIntegerField" required="" id="id_parent_category">
                
                
                
            </div>


            
        </div>
        
        <div class="form-group row form-row field-path">
            
            
            <label for="path" class="col-sm-2 col-form-label"><label class="required" for="id_path">Path:</label></label>
            <div class="col-sm-10">
                

                
                <input type="text" name="path" class="vTextField" maxlength="50" required="" id="id_path">
                
                
                
            </div>


            
        </div>
        
        <div class="form-group row form-row field-description">
            
            
            <label for="description" class="col-sm-2 col-form-label"><label class="required" for="id_description">Description:</label></label>
            <div class="col-sm-10">
                

                
                <input type="text" name="description" class="vTextField" maxlength="50" required="" id="id_description">
                
                
                
            </div>


            
        </div>
        
        <div class="form-group row form-row field-is_active">
            
            
            <label for="is_active" class="col-sm-2 col-form-label"><label for="id_is_active">Is active:</label></label>
            <div class="col-sm-10">
                

                
                <select name="is_active" id="id_is_active">
  <option value="">---------</option>

  <option value="1" selected="">Active</option>

  <option value="0">Inactive</option>

</select>
                
                
                
                <div class="help">1-&gt;Active, 0-&gt;Inactive</div>
                
            </div>


            
        </div>
        
        <div class="form-group row form-row field-deleted">
            
            
            <label for="deleted" class="col-sm-2 col-form-label"><label for="id_deleted">Deleted:</label></label>
            <div class="col-sm-10">
                

                
                <select name="deleted" id="id_deleted">
  <option value="">---------</option>

  <option value="1">yes</option>

  <option value="0" selected="">No</option>

</select>
                
                
                
                <div class="help">1-&gt;yes, 0-&gt;No</div>
                
            </div>


            
        </div>
        
    </div>
</div>
                
                

                

                
                
                

                

                
<div class="submit-row">



<input type="submit" value="Save" class="default" name="_save">






<input type="submit" value="Save and add another" name="_addanother">

<input type="submit" value="Save and continue editing
" name="_continue">




</div>


                
                <script type="text/javascript" id="django-admin-form-add-constants" src="/static/admin/js/change_form.js" data-model-name="category">
                    </script>
                

                
                
<script id="django-admin-prepopulated-fields-constants" src="/static/admin/js/prepopulate_init.js" data-prepopulated-fields="[]">
</script>



            </form>
        </div>
    </div>
</div>
{% endblock %}



templates/event_catagory/catagory_dashboard.html
{% extends 'adminlte/base.html' %}

{% block content %}
Catagory dashboard
{% endblock %}